layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
     - ag_th
     - notebooks

 #social_media:
#  twitter: randomxsk8
  
topics:
  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/python/python.png

  - name: Ruby
    web_url: https://github.com/topics/ruby
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/ruby/ruby.png
    
  - name: HTML
    web_url: https://github.com/topics/html
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/html/html.png
    
  - name: QGIS
    web_url: https://github.com/qgis
    image_url: https://www.3liz.com/en/images/logo-qgis.png
<<<<<<< HEAD
=======
    

theme: jekyll-theme-architect
>>>>>>> 0a70dd9338fc67c30291bd844ad7e4fda4be64e1
